# Generated by Django 5.0.6 on 2024-05-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_account_color_category_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='type',
            new_name='name',
        ),
    ]
